run:
  tests: false
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  skip-files:
    - server/grpc/gogoreflection/serverreflection.go

linters:
  disable-all: true
  enable:
    - dogsled
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1003:"
      linters:
        - stylecheck
    # FIXME: Disabled until golangci-lint updates stylecheck with this fix:
    # https://github.com/dominikh/go-tools/issues/389
    - text: "ST1016:"
      linters:
        - stylecheck
    - path: "migrations"
      text: "SA1019:"
      linters:
        - staticcheck
    - text: "SA1019: sdkerrors.Wrap is deprecated: functionality of this package has been moved to it's own module:"
      linters:
        - staticcheck
    - text: "SA1019: sdkerrors.Wrapf is deprecated: functionality of this package has been moved to it's own module:"
      linters:
        - staticcheck
    - text: "SA1019: errors.Wrap is deprecated: functionality of this package has been moved to it's own module:"
      linters:
        - staticcheck
    - text: "SA1019: errors.Wrapf is deprecated: functionality of this package has been moved to it's own module:"
      linters:
        - staticcheck
    - text: "SA1019: errors.Register is deprecated: functionality of this package has been moved to it's own module:"
      linters:
        - staticcheck
    - text: "SA1019: sdkerrors.Register is deprecated: functionality of this package has been moved to it's own module:"
      linters:
        - staticcheck

  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
